import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {educationalCaseApi,type PublishedCase,type EducationalContent} from '@/services/educationalCaseApi';
export function CaseReading({content}:{content:EducationalContent}){
 return <div className="space-y-5">
  <section><h2 className="text-lg font-semibold">Synthetic scenario</h2><p className="mt-2 whitespace-pre-wrap leading-relaxed text-slate-300">{content.scenario}</p></section>
  <div className="grid gap-5 md:grid-cols-2"><section className="rounded-xl border border-amber-900 bg-amber-950/20 p-5"><h2 className="font-semibold text-amber-200">Original report · intentional issue</h2><p className="mt-3 whitespace-pre-wrap leading-relaxed">{content.originalReport}</p></section><section className="rounded-xl border border-emerald-900 bg-emerald-950/20 p-5"><h2 className="font-semibold text-emerald-200">Correction</h2><p className="mt-3 whitespace-pre-wrap leading-relaxed">{content.correction}</p></section></div>
  <section className="rounded-xl border border-slate-700 bg-slate-900 p-5"><h2 className="font-semibold">What went wrong?</h2><p className="mt-2 whitespace-pre-wrap text-slate-300">{content.reportingIssue}</p><h2 className="mt-5 font-semibold">Explanation</h2><p className="mt-2 whitespace-pre-wrap leading-relaxed text-slate-300">{content.explanation}</p></section>
 </div>;
}
export function EducationalCasesPage(){
 const {caseId}=useParams<{caseId?:string}>();const [cases,setCases]=useState<PublishedCase[]>([]);const [page,setPage]=useState(0);const [busy,setBusy]=useState(true);const [error,setError]=useState('');const [refresh,setRefresh]=useState(0);const [share,setShare]=useState('');const [notice,setNotice]=useState('');
 useEffect(()=>{let active=true;setBusy(true);setError('');setCases([]);setShare('');setNotice('');
 (caseId?educationalCaseApi.publicCase(caseId).then(c=>[c]):educationalCaseApi.published(page)).then(c=>{if(active)setCases(c);}).catch(e=>{if(active)setError(e.response?.status===404?'This case is unavailable or has been withdrawn.':'Could not load educational cases. Please try again.');}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[caseId,page,refresh]);
 async function copy(id:string){const url=new URL(`/cases/${id}`,window.location.origin).toString();setShare(url);try{await navigator.clipboard.writeText(url);setNotice('Case link copied.');}catch{setNotice('Copy the case link below.');}}
 return <main className="min-h-screen bg-[#0a0f1e] px-4 py-7 text-slate-100 sm:px-8"><div className="mx-auto max-w-5xl">
  <nav className="flex flex-wrap justify-between gap-4 border-b border-slate-800 pb-5"><Link className="text-lg font-bold" to="/cases">Med-AI · Educational cases</Link><div className="flex gap-4 text-sm text-cyan-300"><Link to="/demo">Interactive demo</Link><Link to="/pilot">Get free access</Link></div></nav>
  <header className="py-8"><p className="text-xs font-semibold uppercase tracking-widest text-cyan-300">Synthetic cases · Shared learning</p><h1 className="mt-3 text-3xl font-bold">{caseId&&cases[0]?cases[0].content.title:'Reporting lessons worth discussing'}</h1><p className="mt-4 text-slate-300">Explore a reporting issue, its explanation and a correction reviewed by a clinician in Med-AI. These fictional examples are educational, not patient-specific guidance.</p></header>
  {busy&&<p role="status">Loading cases…</p>}{error&&<div role="alert"><p>{error}</p><button className="mt-3 text-cyan-300 underline" onClick={()=>setRefresh(n=>n+1)}>Retry</button></div>}
  {!busy&&!error&&!cases.length&&<section className="rounded-xl border border-slate-700 p-6"><h2 className="font-semibold">No published cases on this page</h2><p className="mt-2 text-slate-300">Cases become available after a clinician reviews the correction and the centre publishes them.</p><Link className="mt-4 inline-block text-cyan-300 underline" to="/demo">Try the synthetic interactive demo</Link></section>}
  {caseId&&cases[0]?<article><p className="mb-5 text-sm text-emerald-200">Synthetic · Clinician-reviewed {new Date(cases[0].reviewedAt).toLocaleDateString()} · Published {new Date(cases[0].publishedAt).toLocaleDateString()}</p><CaseReading content={cases[0].content}/><div className="mt-6 flex gap-5"><button className="rounded-lg bg-cyan-300 px-5 py-3 font-semibold text-slate-950" onClick={()=>void copy(cases[0].id)}>Copy case link</button><Link className="self-center text-cyan-300 underline" to="/cases">All cases</Link></div></article>:
   <div className="grid gap-4 md:grid-cols-2">{cases.map(c=><article key={c.id} className="rounded-xl border border-slate-700 bg-slate-900 p-5"><p className="text-xs text-cyan-300">{c.content.specialty} · SYNTHETIC</p><h2 className="mt-2 text-xl font-semibold"><Link to={`/cases/${c.id}`}>{c.content.title}</Link></h2><p className="mt-3 whitespace-pre-wrap text-sm text-slate-300">{c.content.reportingIssue}</p><p className="mt-4 text-xs text-emerald-200">Clinician-reviewed · {new Date(c.reviewedAt).toLocaleDateString()}</p><Link className="mt-4 inline-block text-cyan-300 underline" to={`/cases/${c.id}`}>Read case and correction →</Link></article>)}</div>}
  {notice&&<p role="status" className="mt-4 text-cyan-200">{notice}</p>}{share&&<label className="mt-3 block text-sm">Shareable case link<input readOnly value={share} onFocus={e=>e.target.select()} className="mt-2 w-full rounded border border-slate-600 bg-slate-900 p-3"/></label>}
  {!caseId&&<div className="mt-6 flex gap-5"><button disabled={busy||page===0} onClick={()=>setPage(p=>p-1)}>Newer</button><button disabled={busy||cases.length<20} onClick={()=>setPage(p=>p+1)}>Older</button></div>}
  <footer className="mt-8 border-t border-slate-800 py-5 text-xs text-slate-400">Clinical review is recorded in Med-AI. Public pages do not expose patient records, internal feedback or reviewer account identifiers.</footer>
 </div></main>;
}
