import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useAuthStore} from '@/stores/authStore';
import {educationalCaseApi,type EducationalContent,type EducationalDraft} from '@/services/educationalCaseApi';
import {demoCases} from '@/demo/clinicalDemo';
import {CaseReading} from './EducationalCasesPage';
const empty:EducationalContent={title:'',specialty:'RADIOLOGY',scenario:'',originalReport:'',reportingIssue:'',explanation:'',correction:'',syntheticOnly:false};
const field='mt-2 w-full rounded-lg border border-slate-600 bg-slate-950 p-3 text-sm';
const button='rounded-lg border border-slate-600 px-4 py-2 text-sm disabled:opacity-50';
export function EducationalCaseEditorPage(){
 const role=useAuthStore(s=>s.role);const permitted=role==='DOCTOR'||role==='HOSPITAL_ADMIN';
 const [drafts,setDrafts]=useState<EducationalDraft[]>([]);const [selected,setSelected]=useState<EducationalDraft|null>(null);const [content,setContent]=useState<EducationalContent>({...empty});const [page,setPage]=useState(0);const [reload,setReload]=useState(0);
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [note,setNote]=useState('');const [confirmed,setConfirmed]=useState(false);const [publishConsent,setPublishConsent]=useState(false);
 useEffect(()=>{let active=true;if(!permitted)return;setBusy(true);setError('');educationalCaseApi.drafts(page).then(d=>{if(active)setDrafts(d);}).catch(()=>{if(active)setError('Could not load draft cases.');}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[page,reload,permitted]);
 const dirty=selected&&JSON.stringify(content)!==JSON.stringify(selected.content);
 function choose(d:EducationalDraft|null){setSelected(d);setContent(d?{...d.content}:{...empty});setConfirmed(false);setPublishConsent(false);setNote('');setError('');setNotice('');}
 async function action(operation:()=>Promise<EducationalDraft>,message:string){setBusy(true);setError('');setNotice('');try{const d=await operation();choose(d);setNotice(message);setReload(n=>n+1);}catch(e){setError((e as {response?:{data?:{message?:string}}}).response?.data?.message||'Action was not confirmed. Your draft is preserved. Reload to check the saved state.');}finally{setBusy(false);}}
 function seed(index:number){choose(null);const c=demoCases[index];const narrative=(r:typeof c.initial)=>`FINDINGS\n${r.findings}\n\nCOMPARISON\n${r.comparison}\n\nIMPRESSION\n${r.impression}`;setContent({title:c.title,specialty:index===0?'RADIOLOGY':'LABORATORY',scenario:c.source.join('\n'),originalReport:narrative(c.initial),reportingIssue:c.task,explanation:index===0?'The source places the effusion on the right. The draft changes the side and its impression contradicts the supplied observation. The revision keeps the side and finding consistent.':'The draft copies the lower reference bound into the measured result. The supplied value is 10.2 g/dL, below the fictional 12.0–16.0 interval. The revision restores the measurement and describes that comparison.',correction:narrative(c.example),syntheticOnly:false});}
 if(!permitted)return <p role="alert">Doctor or Hospital Admin access is required to prepare educational cases.</p>;
 return <div className="max-w-6xl space-y-5"><header><h1 className="text-2xl font-bold">Educational case publishing</h1><p className="mt-2 text-sm text-slate-400">Prepare synthetic examples, review the correction, then publish a public case link. Never copy patient data or private report feedback here.</p><Link className="mt-3 inline-block text-cyan-300 underline" to="/cases">View public case library →</Link></header>
 {error&&<p role="alert" className="text-red-300">{error}</p>}{notice&&<p role="status" className="text-emerald-300">{notice}</p>}
 <div className="flex flex-wrap gap-3"><button disabled={busy} className={button} onClick={()=>choose(null)}>New blank case</button><button disabled={busy} className={button} onClick={()=>seed(0)}>Start radiology example</button><button disabled={busy} className={button} onClick={()=>seed(1)}>Start laboratory example</button><button disabled={busy} className={button} onClick={()=>{choose(null);setReload(n=>n+1);}}>Reload saved cases</button></div>
 <div className="grid items-start gap-5 lg:grid-cols-[1fr_2fr]"><aside className="space-y-3"><h2 className="font-semibold">Your centre’s cases</h2>{!busy&&!drafts.length&&!error&&<p>No saved cases on this page.</p>}{drafts.map(d=><button disabled={busy} key={d.id} className={button+' block w-full text-left'} onClick={()=>choose(d)}>{d.content.title}<span className="mt-1 block text-xs text-cyan-300">{d.status} · v{d.version}</span></button>)}<div className="flex gap-3"><button disabled={busy||page===0} onClick={()=>setPage(p=>p-1)}>Newer</button><button disabled={busy||drafts.length<20} onClick={()=>setPage(p=>p+1)}>Older</button></div></aside>
 <div className="space-y-5"><form onSubmit={e=>{e.preventDefault();void action(()=>selected?educationalCaseApi.edit(selected,content):educationalCaseApi.create(content),'Draft saved. Clinical review is required before publishing.');}} className="rounded-xl border border-slate-700 bg-slate-900 p-5">
 <fieldset disabled={busy||selected?.status==='PUBLISHED'} className="space-y-4"><label className="block">Case title<input className={field} required maxLength={160} value={content.title} onChange={e=>setContent(p=>({...p,title:e.target.value}))}/></label><label className="block">Specialty<select className={field} value={content.specialty} onChange={e=>setContent(p=>({...p,specialty:e.target.value as EducationalContent['specialty']}))}><option>RADIOLOGY</option><option>LABORATORY</option></select></label>
 {([['scenario','Synthetic observations / scenario',5000],['originalReport','Report containing the issue',10000],['reportingIssue','Reporting issue',3000],['explanation','Explanation',10000],['correction','Proposed corrected report',10000]] as const).map(([key,label,max])=><label className="block" key={key}>{label}<textarea className={field} required maxLength={max} rows={4} value={content[key]} onChange={e=>setContent(p=>({...p,[key]:e.target.value}))}/></label>)}
 <label className="flex gap-3 text-sm"><input required type="checkbox" checked={content.syntheticOnly} onChange={e=>setContent(p=>({...p,syntheticOnly:e.target.checked}))}/>I confirm that all content is synthetic and contains no patient information, identifying details or private report excerpts.</label><button disabled={!!selected&&!dirty} type="submit" className={button+' bg-blue-700'}>Save draft</button>
 </fieldset></form>
 <details className="rounded-xl border border-slate-700 p-4"><summary className="cursor-pointer">Preview educational content</summary><div className="mt-4"><CaseReading content={content}/></div></details>
 {selected&&<section className="space-y-4 rounded-xl border border-slate-700 p-5"><h2 className="font-semibold">Review and publication · {selected.status}</h2>{dirty&&<p className="text-amber-200">Save your changes before review. Saving clears previous clinical review.</p>}
 {selected.status==='DRAFT'&&(role==='DOCTOR'?<><label className="block">Clinical review note<textarea className={field} maxLength={3000} value={note} onChange={e=>setNote(e.target.value)}/></label><label className="flex gap-3 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I have reviewed the saved scenario, issue, explanation and correction for educational accuracy and confirmed that the case is synthetic.</label><button disabled={busy||!!dirty||!confirmed||!note.trim()} className={button} onClick={()=>void action(()=>educationalCaseApi.review(selected,note),'Clinical review recorded for this saved version.')}>Record clinical review</button></>:<p>A Doctor account at your centre must review this saved version.</p>)}
 {selected.reviewedAt&&<p className="text-sm text-emerald-200">Reviewed {new Date(selected.reviewedAt).toLocaleString()} · {selected.reviewNote}</p>}
 {selected.status==='REVIEWED'&&<><p className="text-sm text-slate-300">Publishing makes the title, scenario, report issue, explanation and correction publicly accessible. The reviewer’s account identity and review note stay private.</p><label className="flex gap-3 text-sm"><input type="checkbox" checked={publishConsent} onChange={e=>setPublishConsent(e.target.checked)}/>Publish this reviewed synthetic case to the public library.</label><button disabled={busy||!!dirty||!publishConsent} className={button+' bg-cyan-700'} onClick={()=>void action(()=>educationalCaseApi.publish(selected),'Case published. Its public link is ready to share.')}>Publish case</button></>}
 {selected.status==='PUBLISHED'&&<><Link className="block text-cyan-300 underline" to={`/cases/${selected.id}`}>Open shareable case →</Link><p className="text-sm">Published content is read-only. Withdraw it before editing; the next publication requires a new clinical review.</p><button disabled={busy} className={button} onClick={()=>void action(()=>educationalCaseApi.withdraw(selected),'Case withdrawn from the public library. Review is required before republishing.')}>Withdraw from public library</button></>}
 </section>}
 </div></div></div>;
}
