import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useAuthStore} from '@/stores/authStore';
import {pilotResultsApi,type PilotResults} from '@/services/pilotResultsApi';
const today=()=>new Date().toISOString().slice(0,10);
const monthAgo=()=>new Date(Date.now()-29*86400000).toISOString().slice(0,10);
const percent=(part:number,total:number)=>total?`${(100*part/total).toFixed(1)}%`:'Not measured';
const minutes=(value:number|null)=>value===null?'Not measured':`${value.toFixed(1)} min`;
export function PilotResultsPage(){
 const role=useAuthStore(s=>s.role);const allowed=role==='DOCTOR'||role==='HOSPITAL_ADMIN';
 const [from,setFrom]=useState(monthAgo);const [to,setTo]=useState(today);const [range,setRange]=useState({from:monthAgo(),to:today()});const [reload,setReload]=useState(0);
 const [data,setData]=useState<PilotResults|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{let active=true;if(!allowed)return;setBusy(true);setData(null);setError('');pilotResultsApi.get(range.from,range.to).then(d=>{if(active)setData(d);}).catch(()=>{if(active)setError('Could not load pilot results. Choose a date range of up to 366 days and retry.');}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[allowed,range,reload]);
 function download(){if(!data)return;const report={...data,definitions:{qa:'Alert occurrences across QA runs. Latest clinician ratings per alert/run/user, as of generatedAt; not diagnostic accuracy.',editing:'Changed draft saves since trackingSince. Not keystrokes or active editing time. EDITED outcome applies only to explicit sign-off action.',reporting:'Elapsed creation-to-signature minutes for reports signed in UTC range. Includes queue and idle time; not time saved.',adoption:'Current enabled Doctors, Hospital Admins and Lab Techs with QA, draft-save or sign-off activity divided by all current enabled users in those roles.',scope:'Current hospital only; not an enrolled pilot cohort. No baseline/control group.'}};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`pilot-results-${data.from}-${data.to}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 if(!allowed)return <p role="alert">Doctor or Hospital Admin access is required to view pilot results.</p>;
 return <div className="max-w-6xl space-y-6"><header><h1 className="text-2xl font-bold">Pilot results</h1><p className="mt-2 text-sm text-slate-400">Recorded activity for your centre in the selected UTC window. Use these observations to discuss a pilot; they do not establish clinical accuracy or time savings.</p></header>
 <form className="flex flex-wrap items-end gap-4" onSubmit={e=>{e.preventDefault();setRange({from,to});setReload(n=>n+1);}}><label className="text-sm">From (UTC)<input className="mt-1 block rounded border border-slate-600 bg-slate-900 p-2" type="date" required value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">Through (UTC)<input className="mt-1 block rounded border border-slate-600 bg-slate-900 p-2" type="date" required value={to} min={from} onChange={e=>setTo(e.target.value)}/></label><button disabled={busy} className="rounded-lg bg-blue-700 px-4 py-2">{busy?'Loading…':'Apply dates / refresh'}</button><button type="button" disabled={!data||busy} className="rounded-lg border border-slate-600 px-4 py-2 disabled:opacity-50" onClick={download}>Download aggregate results</button></form>
 {error&&<p role="alert" className="text-red-300">{error}</p>}
 {data&&<><p className="text-sm font-semibold">Showing {data.from} through {data.to} (UTC)</p><p className="text-xs text-slate-400">QA and draft-save tracking began {new Date(data.trackingSince).toLocaleString()}. Earlier activity was not backfilled. Refreshed {new Date(data.generatedAt).toLocaleString()}.</p>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
 <Metric title="Useful QA ratings" value={percent(data.qa.useful,data.qa.ratings)} detail={`${data.qa.useful} useful / ${data.qa.ratings} clinician ratings`}><p>{data.qa.rated_alerts} / {data.qa.alerts} alert occurrences rated ({percent(data.qa.rated_alerts,data.qa.alerts)} coverage).</p><p>{data.qa.runs} QA runs across {data.qa.reports} reports. Repeated runs count separately; unrated alerts are not assumed useful.</p></Metric>
 <Metric title="Saved editing revisions" value={data.editing.saves.toString()} detail={`Across ${data.editing.reports} reports with changed draft saves`}><p>{data.editing.reports?(data.editing.saves/data.editing.reports).toFixed(1):'Not measured'} saves per edited report.</p><p>{data.reporting.edited} / {data.reporting.signed} signed reports explicitly marked EDITED. Saving a draft and signing as ACCEPTED is not included in that outcome count. These are effort proxies, not editing minutes.</p></Metric>
 <Metric title="Median reporting turnaround" value={minutes(data.reporting.median_minutes)} detail={`${data.reporting.timed} timed / ${data.reporting.signed} signed reports`}><p>90th percentile: {minutes(data.reporting.p90_minutes)}.</p><p>Creation to signature, including waiting and idle time. Reports still open are excluded. No baseline comparison is available.</p></Metric>
 <Metric title="Active staff adoption" value={percent(data.adoption.active,data.adoption.eligible)} detail={`${data.adoption.active} active / ${data.adoption.eligible} current eligible staff`}><p>Activity means running QA, saving a changed draft or signing. Eligible roles: Doctor, Hospital Admin, Lab Tech.</p><p>This uses today’s enabled roster, not a historical or enrolled-pilot roster. Login alone does not count.</p></Metric>
 </div>
 <section className="rounded-xl border border-slate-700 p-5"><h2 className="font-semibold">Signed reports by day</h2><p className="mt-1 text-xs text-slate-400">UTC dates with sign-offs in the selected window. Missing dates have zero sign-offs.</p>{!data.daily.length?<p className="mt-4 text-sm">No signed reports in this window.</p>:<table className="mt-4 w-full text-left text-sm"><thead><tr><th className="py-2">Date</th><th>Signed reports</th></tr></thead><tbody>{data.daily.map(d=><tr className="border-t border-slate-800" key={d.day}><td className="py-2">{d.day}</td><td>{d.signed}</td></tr>)}</tbody></table>}</section>
 <section className="text-sm text-slate-300"><h2 className="font-semibold">Improve the evidence</h2><p className="mt-2">Run QA on saved reports, select an alert and record Useful or Not useful in the workspace. Save actual draft revisions and complete sign-off through the normal workflow. Rating coverage and small sample sizes matter when interpreting results.</p><Link className="mt-3 inline-block text-cyan-300 underline" to="/worklist">Open Worklist →</Link><p className="mt-3 text-xs text-slate-400">Ratings reflect the latest opinions about runs in the selected window, including ratings added later. Exports contain aggregates and definitions, not patient records or report text.</p></section>
 </>}
 </div>;
}
function Metric({title,value,detail,children}:{title:string;value:string;detail:string;children:React.ReactNode}){return <section className="rounded-xl border border-slate-700 bg-slate-900 p-5"><h2 className="text-sm font-semibold text-slate-300">{title}</h2><p className="mt-3 text-3xl font-bold text-cyan-200">{value}</p><p className="mt-2 text-sm">{detail}</p><div className="mt-4 space-y-2 text-xs leading-relaxed text-slate-400">{children}</div></section>;}
